[providers]
python = "3.11"

[variables]
DJANGO_SETTINGS_MODULE = "tip_predictor.railway_settings"
PYTHONPATH = "/app/tip_predictor"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd tip_predictor",
    "mkdir -p /app/staticfiles",
    "python manage.py collectstatic --noinput --settings=tip_predictor.railway_settings"
]

[start]
cmd = "bash start.sh"
